////////////////////////////////////////////////////////////////////////////
// Porgram: PubGithubData.cs
// Purpose: Data structures definition for Github
// Authors: Antonio Sun (c) 2017, All rights reserved
////////////////////////////////////////////////////////////////////////////

// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

﻿using System;
using System.Collections.Generic;

// !!Rule!!
// The namespace should be Ext.<Module>.<Project>
namespace Ext.Pub.Github
{
    /// ////////////////////////////////////////////////////////////////////////////
    // The data structures are define here
    // ** Usually in spearated files for each class **

    // Ref: 
    // https://api.github.com/search/repositories?q=DotLiquid&sort=stars&order=desc

    /* For comparision.
 
    public class Owner
    {
        public string login;
        public string url;
    }

    public class Item
    {
        public string created_at;
        public string description;
        public bool fork;
        public string full_name;
        public string html_url;
        public string language;
        public string name;
        public int open_issues_count;
        public Owner owner;
        public string pushed_at;
        public double score;
        public int size;
        public int stargazers_count;
        public string updated_at;
        public int watchers_count;
    }

    public class Repos
    {
        public IList<Item> items;
        public int total_count;
    }
    */

    public class Owner
    {
        public string login;
        public string url;
    }

    public class Item
    {
        public string name;
        public string full_name;
        public Owner owner;
        public string html_url;
        public string description;
        public bool fork;
        public string created_at;
        public string updated_at;
        public string pushed_at;
        public int size;
        public int stargazers_count;
        public int watchers_count;
        public string language;
        public int open_issues_count;
        public double score;
    }

    public class Repos
    {
        public int total_count;
        public IList<Item> items;
    }

}

